### ISSUE TITLE
Pedalino Mini 4 MIDI connection

### ISSUE THREAD

**Issue by tybenz** [alf45tar/Pedalino#11]
Is the pedalino mini a USB host? Can I power it with USB AND send USB midi out to control other devices?

If not, can you tell me how to connect a 3.5mm jack or 1/4 jack for TRS-MIDI?

Using the parts list from https://github.com/alf45tar/PedalinoMini-4

**Comment by alf45tar** [comment]
It is not an USB host. Only USB client.
Yes, you can power from USB and control other USB devices but it need to be connected to an USB host.

**Comment by alf45tar** [comment]
https://midi.org/updated-how-to-make-your-own-3-5mm-mini-stereo-trs-to-midi-5-pin-din-cables

**Comment by tybenz** [comment]
Ok thank you!
