### ISSUE TITLE
New logo for your project

### ISSUE THREAD

**Issue by twingenious** [alf45tar/Pedalino#3]
Greetings, @alf45tar 

I'm a designer under construction and an open source enthusiast who exploring GitHub found your awesome project and I wanted to offer a logo for it. We would be working together to create one that fits great with your project. The process is (of course) totally free and you can quit whenever you want. Let me know if you are interested and (if yes) share some ideas you may have (colors, shapes, etc) so I can start working on some sketches. 

Keep up the great work, best regards!

**Comment by alf45tar** [comment]
Sound great.

My preferences are:
- keep it simple
- few colors on the same tone scale

but I am not a designer.
I am open to any idea.

Kind regards
alf45tar

**Comment by twingenious** [comment]
Great! , well the idea is that the logo looks minimalist as you say, but you know, quite original of course.

I'll be sending you some sketches, I have a few in mind that may fit with the project.😃

if you like, you may tell me what you want to appear in the logo, I mean that the MIDI has a lot of things and would be perfect if you tell me what things you wanna show off.💪

**Comment by alf45tar** [comment]
Just a little bit of brainstorming.

- Pedalino is a contraction of Pedal and Arduino but it is also an Italian word. It means sock.

- One of the main feature of Pedalino is that it is completely wireless. No wire is requested because it works on batteries and connected via WiFi or Bluetooth.

**Comment by twingenious** [comment]
![test](https://user-images.githubusercontent.com/43223329/46013300-e5a31680-c099-11e8-80af-6866dbbd462c.png)

What do you think? do you like it?
this is a sketch of the idea, if you like it, you can tell me what colors you prefer to use and we will work with him.
I have made like a hybrid between the Arduino and like a foot controller😃.
quite simple and minimalist for not overload the logo.

**Comment by alf45tar** [comment]
Nice but I don't like the zip idea. It is not original.
Also too complex to me.

**Comment by twingenious** [comment]
I understand, well I have another idea that I want to show you.
![pedalino sizes](https://user-images.githubusercontent.com/43223329/46055876-01e79780-c11c-11e8-80cd-675790e2af77.png)

What do you think?

**Comment by alf45tar** [comment]
Much better.

**Comment by twingenious** [comment]
Working on something

**Comment by twingenious** [comment]
hey, sorry for the delayed answer, I've made some logos and variations. hope you like one, tell me if you like some things of each and I can mix the ideas that you like. 

personally, I like a lot the black one.


![pedalino sizes](https://user-images.githubusercontent.com/43223329/46259390-d01d5a80-c4a6-11e8-9fc4-01306b04fe99.png)
![pedalino sizes 2](https://user-images.githubusercontent.com/43223329/46259431-37d3a580-c4a7-11e8-92b3-8b62f97d00fd.png)
![pedalino sizes 3](https://user-images.githubusercontent.com/43223329/46259392-d14e8780-c4a6-11e8-96e2-c2cfbce3cb2c.png)
![pedalino sizes 4](https://user-images.githubusercontent.com/43223329/46259394-d1e71e00-c4a6-11e8-8fde-1da774ff35a1.png)

**Comment by alf45tar** [comment]
I like the first one: the P on green background.
Can you prepare a version with a white/trasparent background?

Thanks

**Comment by twingenious** [comment]
Done!, I've made the PR,
Check it 😃.

i uploaded the vector files on a <a href="https://drive.google.com/open?id=1ywEvxs4ckiNJ1zxTVY0AvZFHPY-2hrIE">Google Drive</a> folder adding the .SVG .pdf and versions for you to have a full control of your logo

**Comment by alf45tar** [comment]
Thanks @twingenious
