### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by gurnay1973** [alf45tar/Pedalino#7]
Dear, I love this project and I would love to get to the video, but I see advances that I can not find in the sketch. There will be the possibility of uploading the update and also information on how to install the push button (such as push buttons momentary pedal). also sketches of connection of the trs and of the pedals of expression. I am a rookie and I would appreciate your help, please.

**Comment by alf45tar** [comment]
Connect the push button between a digital pin and GND.
More info on https://github.com/alf45tar/Pedalino#pedal-wiring or schematic in PedalinoMini
https://github.com/alf45tar/PedalinoMini/blob/master/images/Schematic_PedalinoMini_Sheet-2.svg
