### ISSUE TITLE
Wont work with current ArduinoJson (V6)

### ISSUE THREAD

**Issue by arduino12** [alf45tar/Pedalino#9]
**Hi,**

**Amazing work!**

I had to change this [line](https://github.com/alf45tar/Pedalino/blob/master/platformio.ini#L37) to `ArduinoJson@5` so it can compile using pio as a quick fix!
Maybe upgrade to v6 with this [guide](https://arduinojson.org/v6/doc/upgrade)?

Arad :)

**Comment by alf45tar** [comment]
Pedalino is discontinued and I will not support anymore.
Use PedalinoMini https://github.com/alf45tar/PedalinoMini. More feautures in a compact form.
